### ISSUE TITLE
Merge Integration Strategy

### ISSUE THREAD

**Issue by MandatedEnd123** [MandatedEnd123/CS471WorkflowsHomeworkAssignment#2]
References user story #1

:bulb: **HINT**: Feel free to click the checkboxes below (which serve as a TODO checklist for the task) as you progress through the instructions

## TODO:
- [ ] :question: Answer question `Task2_Q1` on Canvas
- [ ] :bust_in_silhouette: Assign yourself to this task (this will prompt the [WorkflowLearning GitHub App](https://github.com/apps/workflowlearning) to create the `task_2_merge` branch)
- [ ] :hourglass_flowing_sand: Wait (at most) 60 seconds until the [WorkflowLearning GitHub App](https://github.com/apps/workflowlearning) will comment on this task and confirm that the branch `task_2_merge` was created (refresh the page if you don't see the confirmation comment)
- [ ] [Create a new PR](../compare/task_2_merge?expand=1) having the **base** branch `master` and the **compare** branch `task_2_merge`
- [ ] Edit the description of the PR to reference this task (i.e., the PR description should contain `Closes #2`)
- [ ] :brain: Understand the commits and file changes made in the PR
- [ ] :question: Answer question `Task2_Q2` on Canvas
- [ ] :arrows_counterclockwise: Refresh this page (to ensure that any commits referencing this task are shown on this page) and scroll all the way to the bottom of the page
- [ ] :question: Answer question `Task2_Q3` on Canvas

<h4 align='center'>Starting integration...</h4>

- [ ] In the PR, integrate the changes into `master`
- using the `Merge pull request` option
- with the commit message `Merge pull request #<ID_PR> from <yourGitHubUserName>/task_2_merge` (i.e., the **default** commit message provided by GitHub)

<h4 align='center'>Integration completed.</h4>

- [ ] :eyes: Inspect the history of all the branches and commits in your repository via the GitHub visualization provided in the GitHub tab [`Insights` -> `Network`](../network)
- [ ] :x: In the PR, use the GitHub interface to **delete** the branch (since the branch content was successfully integrated into `master`)
- [ ] :eyes: Inspect the history of all the branches and commits via [`Insights` -> `Network`](../network)
- **NOTE**: even though the branch was deleted, the branch trace is still present, cluttering the repository history
- [ ] :arrows_counterclockwise: Refresh this page (to ensure that any commits referencing this task are shown on this page) and scroll all the way to the bottom of the page
- [ ] :question: Answer question `Task2_Q4` on Canvas
- [ ] :question: Answer question `Task2_Q5` on Canvas
