### ISSUE TITLE
Rebase Integration Strategy

### ISSUE THREAD

**Issue by MandatedEnd123** [MandatedEnd123/CS471WorkflowsHomeworkAssignment#3]
References user story #1

## TODO:
- [ ] :question: Answer question `Task3_Q1` on Canvas
- [ ] :bust_in_silhouette: Assign yourself to this task (this will prompt the [WorkflowLearning GitHub App](https://github.com/apps/workflowlearning) to create the `task_3_rebase` branch)
- [ ] :hourglass_flowing_sand: Wait (at most) 60 seconds until the [WorkflowLearning GitHub App](https://github.com/apps/workflowlearning) will comment on this task and confirm that the branch `task_3_rebase` was created (refresh the page if you don't see the confirmation comment)
- [ ] [Create a new PR](../compare/task_3_rebase?expand=1) having the **base** branch `master` and the **compare** branch `task_3_rebase`
- [ ] Edit the description of the PR to reference this task (i.e., the PR description should contain `Closes #3`)
- [ ] :brain: Understand the commits and file changes made in the PR
- [ ] :question: Answer question `Task3_Q2` on Canvas
- [ ] :arrows_counterclockwise: Refresh this page (to ensure that any commits referencing this task are shown on this page) and scroll all the way to the bottom of the page
- [ ] :question: Answer question `Task3_Q3` on Canvas

<h4 align='center'>Starting integration...</h4>

- [ ] In the PR, integrate the changes into `master`
- using the `Rebase and merge` option

<h4 align='center'>Integration completed.</h4>

- [ ] :eyes: Inspect the history of all the branches and commits via [`Insights` -> `Network`](../network)
- **NOTE**: all the commits from branch `task_3_rebase` were "copied" (rebased) into the `master` branch, cluttering the repository history with multiple commits that contain partial (and incomplete) implementations of the task
- [ ] :x: In the PR, use the GitHub interface to **delete** the branch (since the branch content was successfully integrated into `master`)
- [ ] :eyes: Inspect the history of all the branches and commits via [`Insights` -> `Network`](../network)
- **NOTE**: the branch `task_3_rebase` was deleted successfully from the repository
- [ ] :arrows_counterclockwise: Refresh this page (to ensure that any commits referencing this task are shown on this page) and scroll all the way to the bottom of the page
- [ ] :question: Answer question `Task3_Q4` on Canvas
- [ ] :question: Answer question `Task3_Q5` on Canvas
