### ISSUE TITLE
Squash with Default Message Integration Strategy

### ISSUE THREAD

**Issue by MandatedEnd123** [MandatedEnd123/CS471WorkflowsHomeworkAssignment#4]
References user story #1

## TODO:
- [ ] :question: Answer question `Task4_Q1` on Canvas
- [ ] :bust_in_silhouette: Assign yourself to this task (this will prompt the [WorkflowLearning GitHub App](https://github.com/apps/workflowlearning) to create the `task_4_squash` branch)
- [ ] :hourglass_flowing_sand: Wait (at most) 60 seconds until the [WorkflowLearning GitHub App](https://github.com/apps/workflowlearning) will comment on this task and confirm that the branch `task_4_squash` was created (refresh the page if you don't see the confirmation comment)
- [ ] [Create a new PR](../compare/task_4_squash?expand=1) having the **base** branch `master` and the **compare** branch `task_4_squash`
- [ ] Edit the description of the PR to reference this task
- [ ] :brain: Understand the commits and file changes made in the PR
- [ ] :question: Answer question `Task4_Q2` on Canvas
- [ ] :arrows_counterclockwise: Refresh this page (to ensure that any commits referencing this task are shown on this page) and scroll all the way to the bottom of the page
- [ ] :question: Answer question `Task4_Q3` on Canvas

<h4 align='center'>Starting integration...</h4>

- [ ] In the PR, integrate the changes into `master`
- using the `Squash and merge` option
- with the squashed commit message `Task 4 squash (#<ID_PR>)` (i.e., the **default** commit message provided by GitHub)
**NOTE: do NOT make any changes to the squashed commit extended description (which lists the individual commits that are in the pull request)**

<h4 align='center'>Integration completed.</h4>

- [ ] :eyes: Inspect the history of all the branches and commits via [`Insights` -> `Network`](../network)
- **NOTE**: all the commits from branch `task_4_squash` were squashed/compressed/bundled into a single "atomic" commit that was added to the `master` branch
- [ ] :x: In the PR, use the GitHub interface to **delete** the branch (since the branch content was successfully integrated into `master`)
- [ ] :eyes: Inspect the history of all the branches and commits via [`Insights` -> `Network`](../network)
- **NOTE**: the branch `task_4_squash` was deleted successfully from the repository, reducing the repository clutter
- [ ] :arrows_counterclockwise: Refresh this page (to ensure that any commits referencing this task are shown on this page) and scroll all the way to the bottom of the page
- [ ] :question: Answer question `Task4_Q4` on Canvas
- [ ] :question: Answer question `Task4_Q5` on Canvas
